# Datatypes in numpy

They are indicated by the following:-
i-integer
b-boolean
u-unsigned integer
f-float
c-complex float
m-timedelta
M-datetime
O-object
S-string
U-unicode string
V-fixed chunk of memory for other type ( void )


In [ ]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr.dtype) #This gives us the datatype of the array

int32


In [2]:
arr=np.array(['Apple','banana','cherry'])
print(arr.dtype)

<U6


In [3]:
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [4]:
#Creating an array with data type 4 bytes integer
arr=np.array([1,2,3,4],dtype='i4')
print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [5]:
#Converting datatypes on existing arrays
arr=np.array([1.1,2.2,3.3])
newarr=arr.astype('i') #astype() function creates the copy of the array and allows you to specify the datatype as a parameter
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [7]:
arr=np.array([1.1,2.2,3.1])
newarr=arr.astype(int)
print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [8]:
arr=np.array([1,0,3])
newarr=arr.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


# Numpy array copy vs view

In [ ]:
#Copy
arr=np.array([1,2,3,4])
x=arr.copy()
arr[0]=42
print(arr)
print(x) #Ultimately ythe changes were not done in the copy of the original array 

[42  2  3  4]
[1 2 3 4]


In [ ]:
#View
arr=np.array([1,2,3,4])
x=arr.view()
arr[0]=42
print(arr)
print(x) #In view method the changes are also done to the copy (it can be said otherwise it's just a view of the original one)
#similarly you can also change the value of x. Ex- x[0]=32

[42  2  3  4]
[42  2  3  4]


In [ ]:
#Checking if array owns its data
arr=np.array([1,2,3,4,5])

x=arr.copy()
y=arr.view()

print(x.base)
print(y.base)

#copy return 'none' as it does not own any data of the original array
#whereas view returns the original array as it owns it's data

None
[1 2 3 4 5]


Shape of an array

In [ ]:
#shape is the number of elements in each dimension
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)
#means the array has 2 dimensions where first dimension has 2 elements and second has 4 elements

(2, 4)


In [14]:
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of the array: ',arr.shape)

[[[[[1 2 3 4]]]]]
shape of the array:  (1, 1, 1, 1, 4)


Reshaping an array

In [2]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2) #reshaping 1D into 3D array
print(newarr)
# We can reshape an 8 elements 1D array into 4 elements in 2 rows 2D array 
# but we cannot reshape it into a 3 elements 3 rows 2D array as that would require 3x3 = 9 elements.

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
print(arr.reshape(2,4).base) #Since it returns the original array hence it's a view

[1 2 3 4 5 6 7 8]


In [ ]:
arr=np.array([1,2,3,4,5,6,7,8])
newarr=arr.reshape(2,2,-1) #passing -1 basically means that python will automatically generate the third number for you to pass
print(newarr) #converting 1D array with 8 elements into 3D array with 2X2 elements

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
#Flattening the array means converting a multidimensional array into a 1D array
arr=np.array([[1,2,3],[4,5,6]])
newarr=arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


# Array iteration

In [8]:
import numpy as np
arr=np.array([1,2,3,4,5,6,7,8])
for x in arr:
    print(x)

1
2
3
4
5
6
7
8


In [9]:
arr=np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [10]:
#for printing all the lements manually 
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [11]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [14]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [ ]:
import numpy as np
arr=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
for x in np.nditer(arr): #nditer() is a helping function that can be used from very basic to very advanced iterations. 
#It solves some basic issues which we face in iteration
    print(x)

1
2
3
4
5
6
7
8


np.nditer() is an iterator object used to efficiently iterate through NumPy arrays.

It allows advanced options like changing the data type during iteration or working with multi-dimensional arrays.

In [ ]:
arr=np.array([1,2,3])
for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']): #We actually converted the datatype into string while iterating
    print(x) #and we used a buffer in case we needed it

b'1'
b'2'
b'3'


In [ ]:
#Iterating with different step size
arr=np.array([[1,2,3,4],[5,6,7,8]])
for x in np.nditer(arr[:,::2]): #We skipped step size
    print(x)

1
3
5
7


In [5]:
#Enumerated iteration using ndenumerate()
arr=np.array([1,2,3])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0,) 1
(1,) 2
(2,) 3


In [6]:
arr=np.array([[1,2,3],[4,5,6]])
for idx,x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
