# Numpy joining array

In [2]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [3]:
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[7,8,9],[10,11,12]])
arr=np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


In [4]:
#Joining arrays using stacking 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [5]:
#hstack() method is used to stack along rows
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [7]:
#vstack() to stack along columns
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
#dstack() to stack along height
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Numpy splitting array

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,6])
newarr=np.array_split(arr,3)
print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [2]:
print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [3]:
#Splitting 2D array
arr=np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [4]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15],[16,17,18]])
newarr=np.array_split(arr,3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [ ]:
newarr=np.array_split(arr,3,axis=1) #Splitting 2D arrays into three 2D arrays along columns
print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
#Use the hsplit() method to split the 2-D array into three 2-D arrays along columns
newarr=np.hsplit(arr,3)
print(newarr)
#Similarly vsplit() and dsplit() can also be done

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


# Numpy searching arrays

In [ ]:
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4) #To search an array use the where() method
print(x)

(array([3, 5, 6], dtype=int64),)


In [10]:
x=np.where(arr%2==0)
y=np.where(arr%2==1)
print(x)
print(y)

(array([1, 3, 5, 6], dtype=int64),)
(array([0, 2, 4], dtype=int64),)


In [12]:
#searchsorted() method used on sorted arrays
arr=np.array([6,7,8,9])
x=np.searchsorted(arr,7)
print(x)

1


In [13]:
#Searching from the right side
x=np.searchsorted(arr,7,side='right')
print(x)

2


In [ ]:
#Multiple values
#Q Find the indexes where value 2,4,6 should be inserted
arr=np.array([1,3,5,7])
x=np.searchsorted(arr,[2,4,6])
print(x)

[1 2 3]


Sorting arrays

In [ ]:
arr=np.array([3,2,0,1])
print(np.sort(arr)) #similarly 2D array can also be sorted

[0 1 2 3]


In [ ]:
arr=np.array(['banana','cherry','apple'])
print(np.sort(arr)) 

['apple' 'banana' 'cherry']


Filtering arrays

In [18]:
#Getting some elements out of an existing array and creating a new array out of them is called filtering
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [ ]:
arr=np.array([41,42,43,44])
filter_arr=[]
for element in arr:
    if(element>42):
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(filter_arr)
print(newarr)
#Similarly create a filtered array that returns only even elements from the array

[False, False, True, True]
[43 44]


In [22]:
#Creating filter directly from the array
arr=np.array([41,42,43,44])
arr1=np.array([1,2,3,4,5,6,7])

filter_arr1=arr1%2==0
filter_arr=arr>42

newarr=arr[filter_arr]
newarr1=arr1[filter_arr1]

print(filter_arr)
print(newarr)

print(filter_arr1)
print(newarr1)

[False False  True  True]
[43 44]
[False  True False  True False  True False]
[2 4 6]
